# Generated by Django 3.1.5 on 2021-01-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
    ]
