# Generated by Django 3.1.5 on 2021-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_app', '0004_auto_20210201_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document_attachment',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_attachment',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
